# Generated by Django 5.2.1 on 2025-11-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='img_src',
            field=models.URLField(default='https://picsum.photos/seed/playlist/300', max_length=500),
        ),
    ]
