# Generated by Django 5.2.7 on 2025-11-12 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_playlist_img_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='PERFIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('artista', 'Artista'), ('administrador', 'Administrador'), ('moderador', 'Moderador')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='alertaMODERADOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensajeAlerta', models.TextField()),
                ('fechaEnvio', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_enviadas', to='app.perfil')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_recibidas', to='app.perfil')),
            ],
        ),
    ]
