# Generated by Django 5.2.7 on 2025-11-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_perfil_alertamoderador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="rol",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("artist", "Artist"),
                    ("administrator", "Administrator"),
                    ("moderator", "Moderator"),
                ],
                max_length=15,
            ),
        ),
    ]
